name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Update kubeconfig
        run: aws eks --region ${{ secrets.AWS_DEFAULT_REGION }} update-kubeconfig --name jawan

      - name: Verify kubeconfig path
        run: |
          echo $KUBECONFIG

      - name: Deploy to Kubernetes
        run: |
          kubectl create -f deployment.yaml
          kubectl create -f service.yaml
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }} # Ensure this is correct
